import React from 'react'
import Head from "next/head";
import CarouselComp from "../components/CarouselComp";
import SideBarRight from "../components/SideBarRight";
import Footer from "../components/Footer"
import Navbar from "../components/Navbar";
export default function about() {
  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col  w-full min-h-screen bg-[#ddd7c7] ">
        <Navbar />

        <div className="flex  flex-col  mt-10 items-center  zig-zag-about ">
          <div className="flex flex-col mb-20 items-center ">
            <div>
              <img
                src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2015/02/27.jpg"
                alt="image aaegi "
              />

            </div>
            <div className="bg-white pt-10 max-w-[1080px] pb-20 ">

              <div className="text-center pt-5 pb-8 text-3xl text-[#555]">
                Let's Get Connected
              </div>
              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 ">
                Lorem ipsum dolor sit amet, consetetur sadipscing elitr sed diam nonumy eirmod tempor vuise invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren.
              </p>
              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40  ">
                Cover Photo: Sophie Fontaine
              </p>
             
              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                Name*</p>
              <input className='flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]'  ></input>

              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                Email*</p>
              <input className='flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]'  ></input>


              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                Subject*</p>
              <input className='flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]'  ></input>


              <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                Subject*</p>
              <textarea className='flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-[200px] w-[40%]'  ></textarea>


              


              <div className="flex pt-10 justify-center mb-30 ">

                <svg
                  className="w-6 h-6 mr-5 text-[#CCC] dark:text-white"
                  aria-hidden="true"
                  xmlns="http://www.w3.org/2000/svg"
                  fill="currentColor"
                  viewBox="0 0 8 19"
                >
                  <path
                    fill-rule="evenodd"
                    d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z"
                    clip-rule="evenodd"
                  />
                </svg>
                <svg class="w-6 h-6  mr-5 text-[#CCC] dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 17">
                  <path fill-rule="evenodd" d="M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z" clip-rule="evenodd" />
                </svg>
                <svg class="w-6 h-6 text-[#CCC] mr-5  dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                  <path fill-rule="evenodd" d="M10 0a10 10 0 1 0 10 10A10.009 10.009 0 0 0 10 0Zm6.613 4.614a8.523 8.523 0 0 1 1.93 5.32 20.094 20.094 0 0 0-5.949-.274c-.059-.149-.122-.292-.184-.441a23.879 23.879 0 0 0-.566-1.239 11.41 11.41 0 0 0 4.769-3.366ZM8 1.707a8.821 8.821 0 0 1 2-.238 8.5 8.5 0 0 1 5.664 2.152 9.608 9.608 0 0 1-4.476 3.087A45.758 45.758 0 0 0 8 1.707ZM1.642 8.262a8.57 8.57 0 0 1 4.73-5.981A53.998 53.998 0 0 1 9.54 7.222a32.078 32.078 0 0 1-7.9 1.04h.002Zm2.01 7.46a8.51 8.51 0 0 1-2.2-5.707v-.262a31.64 31.64 0 0 0 8.777-1.219c.243.477.477.964.692 1.449-.114.032-.227.067-.336.1a13.569 13.569 0 0 0-6.942 5.636l.009.003ZM10 18.556a8.508 8.508 0 0 1-5.243-1.8 11.717 11.717 0 0 1 6.7-5.332.509.509 0 0 1 .055-.02 35.65 35.65 0 0 1 1.819 6.476 8.476 8.476 0 0 1-3.331.676Zm4.772-1.462A37.232 37.232 0 0 0 13.113 11a12.513 12.513 0 0 1 5.321.364 8.56 8.56 0 0 1-3.66 5.73h-.002Z" clip-rule="evenodd" />
                </svg>
                

              </div>
              

            </div>
          </div>

        </div>
        <Footer />
      </main>
    </>
  )
}
