import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";
import Navbar from "../components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import Logo from "../../public/logo.png";
import CarouselComp from "../components/CarouselComp";
import SideBarRight from "../components/SideBarRight";
import Footer from "../components/Footer"
import Card from "../components/Card";
export default function Home() {
  const slides1 = [
    {
      url: "https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-8-1080x500.jpg",
    },
    {
      url: "https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-6-1080x500.jpg",
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col  w-full min-h-screen bg-[#ddd7c7] ">
        <Navbar />
        <div className="flex mt-20 justify-center ">
          <Image src={Logo} alt="Logo" priority />
        </div>
        <div className="flex  flex-col  mt-10 items-center ">
          <div className="max-w-[1380px] w-full mb-10">
            <CarouselComp slides={slides1} />
          </div>

          <div className=" flex max-w-[1380px] w-full  ">
            {/* cards div */}
            <div className="w-full pr-10">
              {/* all cards on the left col  */}
              <Card/>
              <Card/>
              <Card/>
              <Card/>
              
           </div>
           {/* right column */}
           <SideBarRight/>
          </div>
        </div>
        <Footer/>
      </main>
    </>
  );
}
