import { useRouter } from "next/router";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Navbar from "../../components/Navbar";
const inter = Inter({ subsets: ["latin"] });
import SideBarRight from "../../components/SideBarRight";
import Footer from "../../components/Footer";
import Card from "../../components/Card";
import Card2 from "../../components/Card2";
import Card3 from "../../components/Card3";
export default function Page() {
  const router = useRouter();
  return (
    <>
      {router.query.name === "bored-at-home" ? (
        <>
          <Head>
            <title>Posts Page </title>
            <meta name="description" content="Generated by create next app" />
            <meta
              name="viewport"
              content="width=device-width, initial-scale=1"
            />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className="flex flex-col  w-full min-h-screen bg-[#ddd7c7] ">
            <Navbar />

            <div className="flex  flex-col  mt-10 items-center ">
              <div className=" flex max-w-[1380px] w-full   ">
                {/* cards div */}
                <div className="w-full pr-10">
                  {/* all cards on the left col  */}
                  <div className="flex flex-col mb-20 zig-zag-card ">
                    <div>
                      <img
                        src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-6-1080x500.jpg"
                        alt="image aaegi "
                      />
                    </div>
                    <div className="bg-white pt-10 ">
                      <div className="flex w-full ">
                        <h6 className="italic  mr-auto ml-20 text-[#777]">
                          🕛 June 22, 2023
                        </h6>
                        <h6 className="ml-auto mr-20">
                          {" "}
                          <span className="italic  text-[#777]">
                            🖋️ by{" "}
                          </span>{" "}
                          <a href="#">Nolan</a>
                        </h6>
                      </div>
                      <div className="text-center pt-5 pb-8 text-3xl text-[#555]">
                        Bored at Home{" "}
                      </div>
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 ">
                        Consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat,
                        sed diam voluptua. At vero eos et accusam et justo duo
                        dolores et ea rebum. Stet clita kasd gubergren, no sea
                        takimata sanctus est Lorem ipsum dolor sit amet. Lorem
                        ipsum dolor sit amet, consetetur sadipscing.
                      </p>
                      <div className="px-20 pt-5 pb-8 text-3xl text-[#555]">
                        Standard Post
                      </div>
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 ">
                        Consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat,
                        sed diam voluptua. At vero eos et accusam et justo duo
                        dolores et ea rebum. Stet clita kasd gubergren, no sea
                        takimata sanctus est Lorem ipsum dolor sit amet. Lorem
                        ipsum dolor sit amet, consetetur sadipscing.
                      </p>
                      <img
                        alt="image "
                        src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/74ecfb62a7d04c8a35182938dfaa18d5.jpg"
                        className="px-20 w-full"
                      />
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 pt-5 ">
                        She packed her seven versalia, put her initial into the
                        belt and made herself on the way. When she reached the
                        first hills of the Italic Mountains, she had a last view
                        back on the skyline of her hometown Bookmarksgrove, the
                        headline of Alphabet Village and the subline of her own
                        road, the Line Lane. Even the all-powerful Pointing has
                        no control about the blind texts it is an almost
                        unorthographic life One day however a small line of
                        blind text.
                      </p>
                      <div className="relative ml-5">
                        <div class="absolute left-[120px] w-1 bg-[#1c7791] h-[65px]  bg-blue-600"></div>
                        <p className=" flex font-[1.4em] leading-8 text-[#444] w-[100%] px-40 mt-4 italic">
                          Duis autem vel eum iriure dolor in hendrerit in
                          vulputate velit esse molestie consequat, vel illum
                          dolore.
                        </p>
                      </div>
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 pt-5 ">
                        She packed her seven versalia, put her initial into the
                        belt and made herself on the way. When she reached the
                        first hills of the Italic Mountains, she had a last view
                        back on the skyline of her hometown Bookmarksgrove, the
                        headline of Alphabet Village and the subline of her own
                        road, the Line Lane. Even the all-powerful Pointing has
                        no control about the blind texts it is an almost
                        unorthographic life One day however a small line of
                        blind text.
                      </p>
                      <div className="px-20 pt-5 pb-8 text-3xl text-[#555]">
                        Heading 2
                      </div>
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 ">
                        Consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat,
                        sed diam voluptua. At vero eos et accusam et justo duo
                        dolores et ea rebum. Stet clita kasd gubergren, no sea
                        takimata sanctus est Lorem ipsum dolor sit amet. Lorem
                        ipsum dolor sit amet, consetetur sadipscing.
                      </p>
                      <div className="px-20">
                        <iframe
                          className="w-full h-[40vh]"
                          src="https://www.youtube.com/embed/gYu2dEju6bI"
                          title="YouTube video player"
                          frameborder="0"
                          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                          allowfullscreen
                        ></iframe>
                      </div>
                      <p className=" flex font-[1.4em] leading-8 text-[#444] px-20 pt-5">
                        Consetetur sadipscing elitr, sed diam nonumy eirmod
                        tempor invidunt ut labore et dolore magna aliquyam erat,
                        sed diam voluptua. At vero eos et accusam et justo duo
                        dolores et ea rebum. Stet clita kasd gubergren, no sea
                        takimata sanctus est Lorem ipsum dolor sit amet. Lorem
                        ipsum dolor sit amet, consetetur sadipscing.
                      </p>
                      <div className="flex pt-10 justify-center">
                        <svg
                          className="w-6 h-6 mr-5 text-[#CCC] dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="currentColor"
                          viewBox="0 0 8 19"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z"
                            clip-rule="evenodd"
                          />
                        </svg>
                        <svg
                          class="w-6 h-6  mr-5 text-[#CCC] dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="currentColor"
                          viewBox="0 0 20 17"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z"
                            clip-rule="evenodd"
                          />
                        </svg>
                        <svg
                          class="w-6 h-6 text-[#CCC] mr-5  dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="currentColor"
                          viewBox="0 0 20 20"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M10 0a10 10 0 1 0 10 10A10.009 10.009 0 0 0 10 0Zm6.613 4.614a8.523 8.523 0 0 1 1.93 5.32 20.094 20.094 0 0 0-5.949-.274c-.059-.149-.122-.292-.184-.441a23.879 23.879 0 0 0-.566-1.239 11.41 11.41 0 0 0 4.769-3.366ZM8 1.707a8.821 8.821 0 0 1 2-.238 8.5 8.5 0 0 1 5.664 2.152 9.608 9.608 0 0 1-4.476 3.087A45.758 45.758 0 0 0 8 1.707ZM1.642 8.262a8.57 8.57 0 0 1 4.73-5.981A53.998 53.998 0 0 1 9.54 7.222a32.078 32.078 0 0 1-7.9 1.04h.002Zm2.01 7.46a8.51 8.51 0 0 1-2.2-5.707v-.262a31.64 31.64 0 0 0 8.777-1.219c.243.477.477.964.692 1.449-.114.032-.227.067-.336.1a13.569 13.569 0 0 0-6.942 5.636l.009.003ZM10 18.556a8.508 8.508 0 0 1-5.243-1.8 11.717 11.717 0 0 1 6.7-5.332.509.509 0 0 1 .055-.02 35.65 35.65 0 0 1 1.819 6.476 8.476 8.476 0 0 1-3.331.676Zm4.772-1.462A37.232 37.232 0 0 0 13.113 11a12.513 12.513 0 0 1 5.321.364 8.56 8.56 0 0 1-3.66 5.73h-.002Z"
                            clip-rule="evenodd"
                          />
                        </svg>
                        <svg
                          class="w-6 h-6 text-[#CCC]  dark:text-white"
                          aria-hidden="true"
                          xmlns="http://www.w3.org/2000/svg"
                          fill="none"
                          viewBox="0 0 20 18"
                        >
                          <path
                            stroke="currentColor"
                            stroke-linecap="round"
                            stroke-linejoin="round"
                            stroke-width="2"
                            d="M16 5h2a1 1 0 0 1 1 1v7a1 1 0 0 1-1 1h-2v3l-4-3H8m4-13H2a1 1 0 0 0-1 1v7a1 1 0 0 0 1 1h2v3l4-3h4a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1Z"
                          />
                        </svg>
                      </div>
                      <div className="text-center py-10 pb-8  text-[#777] ">
                        Category :
                        <span className="text-[#1C7791]">Vintage</span>
                      </div>
                    </div>
                  </div>
                  <div className="flex flex-col items-center w-full h-auto bg-white mb-20 p-10 ">
                    <h1 className="text-4xl mb-10">Related Posts</h1>
                    <div className="flex ">
                      <div className="w-[55%] flex flex-col items-center">
                        <img
                          className=" w-full"
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-6-1080x500.jpg"
                        />{" "}
                        <h3 className="pt-5 hover:text-[#CCC] "> Title</h3>
                      </div>
                      <div className="w-[55%] mx-4  flex flex-col items-center">
                        <img
                          className=" w-full"
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-6-1080x500.jpg"
                        />
                        <h3 className="pt-5 hover:text-[#CCC]">Title</h3>
                      </div>
                      <div className="w-[55%] flex flex-col items-center">
                        <img
                          className=" w-full"
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-slider-6-1080x500.jpg"
                        />{" "}
                        <h3 className="pt-5 hover:text-[#CCC]">Title</h3>
                      </div>
                    </div>
                  </div>
                  <div className="bg-white pt-10 max-w-[1013px] pb-20 ">
                    <div className="text-center pt-5 pb-8 text-2xl text-[#555]">
                      3 Comments
                    </div>
                    <div className="flex flex-col px-40">
                      <div className="flex py-8">
                        <img
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-16-88x60.jpg"
                          alt="latest post img"
                        />
                        <div className="flex flex-col ml-5">
                          <h4 className="text-l"> Visitor</h4>
                          <h6 className="italic  text-[#777]">June 22, 2023</h6>
                        </div>
                        <span className="ml-auto mr-5">Reply +</span>
                      </div>
                      <div className="flex py-8">
                        <img
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-16-88x60.jpg"
                          alt="latest post img"
                        />
                        <div className="flex flex-col ml-5">
                          <h4 className="text-l"> Visitor</h4>
                          <h6 className="italic  text-[#777]">June 22, 2023</h6>
                        </div>
                        <span className="ml-auto mr-5">Reply +</span>
                      </div>
                      <div className="flex py-8">
                        <img
                          src="https://theburnhambox.com/frida/wp-content/uploads/sites/14/2019/01/frida-16-88x60.jpg"
                          alt="latest post img"
                        />
                        <div className="flex flex-col ml-5">
                          <h4 className="text-l"> Visitor</h4>
                          <h6 className="italic  text-[#777]">June 22, 2023</h6>
                        </div>
                        <span className="ml-auto mr-5">Reply +</span>
                      </div>
                    </div>

                    <div className=" flex px-40 pt-20 pb-5 text-2xl text-[#555]">
                      Leave a Reply
                      <span className="ml-auto mr-5 text-xl">cancel reply <span className="font-bold">x</span> </span>
                    </div>
                    <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                      Comment
                    </p>
                    <textarea className="flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-[200px] w-[65%]"></textarea>

                    <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                      Name*
                    </p>
                    <input className="flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]"></input>

                    <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                      Email*
                    </p>
                    <input className="flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]"></input>

                    <p className=" flex font-[1.4em] leading-8 text-[#444] px-40 mt-4">
                      Website
                    </p>
                    <input className="flex font-[1.4em] leading-8 text-[#444] px-40 mt-4 mb-2 bg-gray-300 ml-40 h-auto w-[30%]"></input>

                    <div className="flex pt-10 justify-center mb-30 ">
                      <svg
                        className="w-6 h-6 mr-5 text-[#CCC] dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 8 19"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M6.135 3H8V0H6.135a4.147 4.147 0 0 0-4.142 4.142V6H0v3h2v9.938h3V9h2.021l.592-3H5V3.591A.6.6 0 0 1 5.592 3h.543Z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <svg
                        class="w-6 h-6  mr-5 text-[#CCC] dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 17"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M20 1.892a8.178 8.178 0 0 1-2.355.635 4.074 4.074 0 0 0 1.8-2.235 8.344 8.344 0 0 1-2.605.98A4.13 4.13 0 0 0 13.85 0a4.068 4.068 0 0 0-4.1 4.038 4 4 0 0 0 .105.919A11.705 11.705 0 0 1 1.4.734a4.006 4.006 0 0 0 1.268 5.392 4.165 4.165 0 0 1-1.859-.5v.05A4.057 4.057 0 0 0 4.1 9.635a4.19 4.19 0 0 1-1.856.07 4.108 4.108 0 0 0 3.831 2.807A8.36 8.36 0 0 1 0 14.184 11.732 11.732 0 0 0 6.291 16 11.502 11.502 0 0 0 17.964 4.5c0-.177 0-.35-.012-.523A8.143 8.143 0 0 0 20 1.892Z"
                          clip-rule="evenodd"
                        />
                      </svg>
                      <svg
                        class="w-6 h-6 text-[#CCC] mr-5  dark:text-white"
                        aria-hidden="true"
                        xmlns="http://www.w3.org/2000/svg"
                        fill="currentColor"
                        viewBox="0 0 20 20"
                      >
                        <path
                          fill-rule="evenodd"
                          d="M10 0a10 10 0 1 0 10 10A10.009 10.009 0 0 0 10 0Zm6.613 4.614a8.523 8.523 0 0 1 1.93 5.32 20.094 20.094 0 0 0-5.949-.274c-.059-.149-.122-.292-.184-.441a23.879 23.879 0 0 0-.566-1.239 11.41 11.41 0 0 0 4.769-3.366ZM8 1.707a8.821 8.821 0 0 1 2-.238 8.5 8.5 0 0 1 5.664 2.152 9.608 9.608 0 0 1-4.476 3.087A45.758 45.758 0 0 0 8 1.707ZM1.642 8.262a8.57 8.57 0 0 1 4.73-5.981A53.998 53.998 0 0 1 9.54 7.222a32.078 32.078 0 0 1-7.9 1.04h.002Zm2.01 7.46a8.51 8.51 0 0 1-2.2-5.707v-.262a31.64 31.64 0 0 0 8.777-1.219c.243.477.477.964.692 1.449-.114.032-.227.067-.336.1a13.569 13.569 0 0 0-6.942 5.636l.009.003ZM10 18.556a8.508 8.508 0 0 1-5.243-1.8 11.717 11.717 0 0 1 6.7-5.332.509.509 0 0 1 .055-.02 35.65 35.65 0 0 1 1.819 6.476 8.476 8.476 0 0 1-3.331.676Zm4.772-1.462A37.232 37.232 0 0 0 13.113 11a12.513 12.513 0 0 1 5.321.364 8.56 8.56 0 0 1-3.66 5.73h-.002Z"
                          clip-rule="evenodd"
                        />
                      </svg>
                    </div>
                  </div>
                </div>
                {/* right column */}
                <SideBarRight />
              </div>
            </div>
            <Footer />
          </main>
        </>
      ) : (
        <div>PAGE NOT FOUND </div>
      )}
    </>
  );
}
